//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int book_id { get; set; }
        public string isbn { get; set; }
        public string book_title { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
        public Nullable<int> quantity { get; set; }
        public string image { get; set; }
        public Nullable<double> price { get; set; }
    }
}
