//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class issuebook
    {
        public int issuebook1 { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> bookid { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public System.DateTime returndate { get; set; }
        public Nullable<int> Fine { get; set; }
    }
}
