//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string arid_no { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string full_name { get; set; }
        public string father_name { get; set; }
        public string profile_pic { get; set; }
        public string user_type { get; set; }
        public string degree { get; set; }
        public string section { get; set; }
        public Nullable<int> semester { get; set; }
        public string city { get; set; }
    }
}
